name: update_submodules

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Pull submodules
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main --recurse-submodules
          git add .
          git commit -m "Update submodules" && git push
