name: update_submodules

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Pull submodules
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          cd r-announce && git checkout main && git pull && cd ..
          cd r-devel && git checkout main && git pull && cd ..
          cd r-help && git checkout main && git pull && cd ..
          cd r-package-devel && git checkout main && git pull && cd ..
          cd r-packages && git checkout main && git pull && cd ..
          git commit -am "Update submodules" && git push
